sudo: enabled
dist: xenial
language: python
jobs:
  include:
    - name: '3.6'
      python: '3.6'
      install:
        - pip install pipenv
        - pipenv install --dev
      script:
        - pipenv run pytest sosw/test/suite_unit.py

deploy:
  provider: pypi
  skip_existing: true
  user: ngr
  password:
    secure: adv5/8DlaCiKKdBR4W44ortGpOmoVsWsTvXU4A+pCWinVsA1Qd3saV4UPGTkNiakmPFtEue3IpeYUEwVtBP1MdMlwAu3TR/Ug77NPhR38Z7oAWjBziWMGVUxofvPBS4qbD2m/Yh9qj3NeIkalfjjIonv0W49/AHqtLzsCXy9Pn+x06GU37f+5VgTs0dVJgD3vIM1DHlXNXosRdos7q66D8wSy6xNlmT8kPXiOGfzTgoVtE1TyiLD8uVwK5+Ius8wOo+QdDZv5RW8wLIBObRIP2KyhRg7bUrZXWRSrPzJPVbxpZsvI8rujuduY2wtD8RIsPuviDcXqY4XOt5dsuLcSOJGjZZJEPabG9T18HNbrqqhmgkJ05dF63N5LA2X0jW7Zk5JO7UQaf4dBHxvcPI3Y6U0qtC5S+csFBlf9tcxJoryjC6TO4P6bTRLmpmm9YdPjZYUzk9QG+g9kJs4SGuqvQParL+S4NAHAiUHv/91/6qklb+H5+lUsw7LXbuL1A5o8SuYyzvXXCALLZAQrWZ9s+JJqHDzL8iqto2XO73KVk0tS40xsLCdB7qBx7voh1tkc9RK30WOAOHK1ZDST3jTPHUGBtiUysuXRzfivpOY5/q2KH6miTWIa2CR2J/D7F5ExyQ1ZXIniTlbotfh78lZJKi1Ld+yKzgvxkguaSLltNg=
  on:
    branch: master
